# Generated by Django 5.2.5 on 2026-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("teacher", "Teacher"),
                    ("researcher", "Researcher"),
                    ("council", "Council"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
